const manufacturers = new Map([
  ['AM', 'AMD'],
  ['AK', 'ASROCK'],
  ['AS', 'ASUS'],
  ['BI', 'BIOSTAR'],
  ['EV', 'EVGA'],
  ['GB', 'GIGABYTE'],
  ['MS', 'MSI'],
  ['NV', 'NVIDIA'],
  ['PL', 'PALIT'],
  ['PN', 'PNY'],
  ['PC', 'POWERCOLOR'],
  ['SP', 'SAPPHIRE'],
  ['ZO', 'ZOTAC'],
  ['XF', 'XFX'],
  ['IN', 'INTEL'],
  ['AC', 'ACER'],
  ['AD', 'ADATA'],
  ['CO', 'CORSAIR'],
  ['CR', 'CRUCIAL'],
  ['GK', 'GSKILL'],
  ['HX', 'HYPERX'],
  ['KS', 'KINGSTON'],
  ['PT', 'PATRIOT'],
  ['TG', 'TEAMGROUP'],
  ['SG', 'SAMSUNG'],
  ['SE', 'SEAGATE'],
  ['WD', 'WD'],
  ['SD', 'SANDISK'],
  ['BQ', 'BE QUIET!'],
  ['CM', 'COOLER MASTER'],
  ['SN', 'SEASONIC'],
  ['TL', 'THERMALAKE'],
  ['NT', 'NOCTUA'],
  ['DC', 'DEEPCOOL'],
  ['NX', 'NZXT'],
  ['FD', 'FRACTAL DESIGN'],
  ['LN', 'LENOVO'],
])

module.exports = manufacturers
