const manufacturers = new Map([
  ['AMD', 'AM'],
  ['ASROCK', 'AK'],
  ['ASUS', 'AS'],
  ['BIOSTAR', 'BI'],
  ['EVGA', 'EV'],
  ['GIGABYTE', 'GB'],
  ['MSI', 'MS'][('NVIDIA', 'NV')],
  ['PALIT', 'PL'],
  ['PNY', 'PN'],
  ['POWERCOLOR', 'PC'],
  ['SAPPHIRE', 'SP'],
  ['ZOTAC', 'ZO'],
  ['XFX', 'XF'],
  ['INTEL', 'IN'],
  ['ACER', 'AC'],
  ['ADATA', 'AD'],
  ['CORSAIR', 'CO'],
  ['CRUCIAL', 'CR'],
  ['GSKILL', 'GK'],
  ['HYPERX', 'HX'],
  ['KINGSTON', 'KS'],
  ['PATRIOT', 'PT'],
  ['TEAMGROUP', 'TG'],
  ['SAMSUNG', 'SG'],
  ['SEAGATE', 'SE'],
  ['WD', 'WD'],
  ['SANDISK', 'SD'],
  ['BE QUIET!', 'BQ'],
  ['COOLER MASTER', 'CM'],
  ['SEASONIC', 'SN'],
  ['THERMALAKE', 'TL'],
  ['NOCTUA', 'NT'],
  ['DEEPCOOL', 'DC'],
  ['NZXT', 'NX'],
  ['FRACTAL DESIGN', 'FD'],
  ['LENOVO', 'LN'],
])

module.exports = manufacturers
